using System.Text;
using System.Threading;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates the auto-emitted async sibling interface for a <see cref="ServiceModel"/>.
/// For every synchronous method on the user's interface, the sibling exposes a non-blocking
/// counterpart returning <see cref="System.Threading.Tasks.Task"/> /
/// <see cref="System.Threading.Tasks.Task{TResult}"/> with an optional
/// <see cref="System.Threading.CancellationToken"/>. Already-asynchronous methods are
/// included unchanged so the sibling is a complete async-only view of the service.
/// </summary>
internal static class AsyncInterfaceGenerator
{
    public static string Generate(
        ServiceModel service,
        EquatableArray<AsyncSiblingMethod> siblingMethods,
        CancellationToken ct = default)
    {
        var siblingName = NamingHelpers.AsyncSiblingInterfaceName(service.InterfaceName);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {IdentifierHelpers.EscapeNamespace(service.Namespace)}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Auto-generated async sibling of <see cref=\"{service.InterfaceName}\"/>. Use this");
        sb.AppendLine($"    /// interface from callers that must not block on RPC calls.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public interface {IdentifierHelpers.EscapeIdentifier(siblingName)}");
        sb.AppendLine("    {");

        var first = true;
        foreach (var s in siblingMethods.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (s.Source.UnsupportedReason is not null)
            {
                // The sync method couldn't be marshalled in the first place — there's no point
                // re-exposing a throwing stub on the async sibling.
                continue;
            }

            if (!first) sb.AppendLine();
            first = false;
            EmitSignature(sb, s, ct);
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitSignature(
        StringBuilder sb,
        AsyncSiblingMethod s,
        CancellationToken ct)
    {
        var returnText = NamingHelpers.GetDeclaredReturnTypeText(s.SiblingReturnKind, s.Source.UnwrappedReturnType);

        var paramList = new StringBuilder();
        for (var i = 0; i < s.Parameters.Count; i++)
        {
            ct.ThrowIfCancellationRequested();

            if (i > 0) paramList.Append(", ");
            var p = s.Parameters[i];
            paramList.Append(p.RefKindKeyword).Append(p.Type).Append(' ').Append(p.Name);
            if (p.IsCancellationToken && p.HasDefaultValue)
            {
                paramList.Append(" = default");
            }
        }

        sb.AppendLine($"        {returnText} {s.Name}({paramList});");
    }
}
