using System.Text;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates server dispatcher classes for ShaRPC services. The dispatcher's
/// <c>DispatchAsync</c> is itself async, but it calls the user's service method using
/// the exact shape declared on the interface (sync vs async, with or without a
/// <see cref="System.Threading.CancellationToken"/>).
/// </summary>
internal static class DispatcherGenerator
{
    public static string Generate(ServiceModel service)
    {
        var sb = new StringBuilder();
        var dispatcherName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Dispatcher";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ShaRPC.Core.Serialization;");
        sb.AppendLine("using ShaRPC.Core.Server;");
        sb.AppendLine("using ShaRPC.Core.Exceptions;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Server dispatcher for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {dispatcherName} : IServiceDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {service.InterfaceName} _service;");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}({service.InterfaceName} service)");
        sb.AppendLine("        {");
        sb.AppendLine("            _service = service ?? throw new ArgumentNullException(nameof(service));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public string ServiceName => \"{service.ServiceName}\";");
        sb.AppendLine();
        // CS1998 is suppressed because services whose methods are all synchronous would
        // otherwise leave the async DispatchAsync with no `await`. The signature must
        // remain async to satisfy IServiceDispatcher.
        sb.AppendLine("#pragma warning disable CS1998");
        sb.AppendLine("        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)");
        sb.AppendLine("#pragma warning restore CS1998");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (method)");
        sb.AppendLine("            {");

        foreach (var m in service.Methods.Array)
        {
            GenerateDispatchCase(sb, m);
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new ShaRpcNotFoundException($\"Method '{{method}}' not found on service '{service.ServiceName}'.\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GenerateDispatchCase(StringBuilder sb, MethodModel method)
    {
        sb.AppendLine($"                case \"{method.RpcName}\":");
        sb.AppendLine("                {");

        // Build the call argument list: user-declared parameters, then `ct` if the interface
        // declared a CancellationToken parameter.
        var argList = new StringBuilder();
        if (method.Parameters.Count == 1)
        {
            sb.AppendLine($"                    var arg = serializer.Deserialize<{method.Parameters[0].Type}>(payload);");
            argList.Append("arg");
        }
        else if (method.Parameters.Count > 1)
        {
            var tupleTypes = new StringBuilder();
            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0)
                {
                    tupleTypes.Append(", ");
                }
                tupleTypes.Append(method.Parameters[i].Type);
            }

            sb.AppendLine($"                    var args = serializer.Deserialize<({tupleTypes})>(payload);");

            for (var i = 0; i < method.Parameters.Count; i++)
            {
                if (i > 0)
                {
                    argList.Append(", ");
                }
                argList.Append("args.Item").Append(i + 1);
            }
        }

        if (method.HasCancellationToken)
        {
            if (argList.Length > 0)
            {
                argList.Append(", ");
            }
            argList.Append("ct");
        }

        var call = $"_service.{method.Name}({argList})";

        switch (method.ReturnKind)
        {
            case MethodReturnKind.Void:
                sb.AppendLine($"                    {call};");
                sb.AppendLine("                    return Array.Empty<byte>();");
                break;

            case MethodReturnKind.Sync:
                sb.AppendLine($"                    var result = {call};");
                sb.AppendLine("                    return serializer.Serialize(result);");
                break;

            case MethodReturnKind.Task:
                sb.AppendLine($"                    await {call};");
                sb.AppendLine("                    return Array.Empty<byte>();");
                break;

            case MethodReturnKind.TaskOf:
                sb.AppendLine($"                    var result = await {call};");
                sb.AppendLine("                    return serializer.Serialize(result);");
                break;
        }

        sb.AppendLine("                }");
    }
}
