using System.Text;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates server dispatcher classes for ShaRPC services.
/// </summary>
internal static class DispatcherGenerator
{
    public static string Generate(ServiceInfo service)
    {
        var sb = new StringBuilder();
        var dispatcherName = service.InterfaceName.StartsWith("I")
            ? service.InterfaceName.Substring(1) + "Dispatcher"
            : service.InterfaceName + "Dispatcher";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ShaRPC.Core.Serialization;");
        sb.AppendLine("using ShaRPC.Core.Server;");
        sb.AppendLine("using ShaRPC.Core.Exceptions;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Server dispatcher for {service.InterfaceName}.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public sealed class {dispatcherName} : IServiceDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {service.InterfaceName} _service;");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}({service.InterfaceName} service)");
        sb.AppendLine("        {");
        sb.AppendLine("            _service = service ?? throw new ArgumentNullException(nameof(service));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public string ServiceName => \"{service.ServiceName}\";");
        sb.AppendLine();
        sb.AppendLine("        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (method)");
        sb.AppendLine("            {");

        foreach (var method in service.Methods)
        {
            GenerateDispatchCase(sb, method);
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new ShaRpcNotFoundException($\"Method '{{method}}' not found on service '{service.ServiceName}'.\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GenerateDispatchCase(StringBuilder sb, MethodInfo method)
    {
        sb.AppendLine($"                case \"{method.RpcName}\":");
        sb.AppendLine("                {");

        if (method.Parameters.Count == 0)
        {
            // No parameters
            if (method.ReturnsVoid)
            {
                sb.AppendLine($"                    await _service.{method.Name}(ct);");
                sb.AppendLine("                    return Array.Empty<byte>();");
            }
            else
            {
                sb.AppendLine($"                    var result = await _service.{method.Name}(ct);");
                sb.AppendLine("                    return serializer.Serialize(result);");
            }
        }
        else if (method.Parameters.Count == 1)
        {
            // Single parameter
            var param = method.Parameters[0];
            sb.AppendLine($"                    var arg = serializer.Deserialize<{param.Type}>(payload);");

            if (method.ReturnsVoid)
            {
                sb.AppendLine($"                    await _service.{method.Name}(arg, ct);");
                sb.AppendLine("                    return Array.Empty<byte>();");
            }
            else
            {
                sb.AppendLine($"                    var result = await _service.{method.Name}(arg, ct);");
                sb.AppendLine("                    return serializer.Serialize(result);");
            }
        }
        else
        {
            // Multiple parameters - unwrap from tuple
            var tupleTypes = string.Join(", ", method.Parameters.ConvertAll(p => p.Type));
            sb.AppendLine($"                    var args = serializer.Deserialize<({tupleTypes})>(payload);");

            var argList = new System.Collections.Generic.List<string>();
            for (int i = 0; i < method.Parameters.Count; i++)
            {
                argList.Add($"args.Item{i + 1}");
            }
            var argsString = string.Join(", ", argList);

            if (method.ReturnsVoid)
            {
                sb.AppendLine($"                    await _service.{method.Name}({argsString}, ct);");
                sb.AppendLine("                    return Array.Empty<byte>();");
            }
            else
            {
                sb.AppendLine($"                    var result = await _service.{method.Name}({argsString}, ct);");
                sb.AppendLine("                    return serializer.Serialize(result);");
            }
        }

        sb.AppendLine("                }");
    }
}
