using System.Collections.Generic;
using System.Text;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates server dispatcher classes for ShaRPC services. The dispatcher's
/// <c>DispatchAsync</c> is itself async, but it calls the user's service method using
/// the exact shape declared on the interface (sync vs async, with or without a
/// <see cref="System.Threading.CancellationToken"/>). All emitted type references are
/// fully qualified. When a service method's return type is itself a
/// <c>[ShaRpcService]</c> interface the dispatcher registers the returned instance with
/// the per-connection <see cref="ShaRPC.Core.Server.IInstanceRegistry"/> and serializes a
/// <see cref="ShaRPC.Core.Protocol.ServiceHandle"/> in its place. Every dispatcher also
/// emits a <c>DispatchOnInstanceAsync</c> override that resolves a registered instance
/// and runs the same switch against it — so any service may be reached as a sub-service.
/// </summary>
internal static class DispatcherGenerator
{
    public static string Generate(ServiceModel service)
    {
        var sb = new StringBuilder();
        var dispatcherName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Dispatcher";
        var qualifiedInterface = QualifyServiceType(service, service.InterfaceName);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Server dispatcher for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {dispatcherName} : global::ShaRPC.Core.Server.IServiceDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly {qualifiedInterface} _service;");
        sb.AppendLine();
        sb.AppendLine($"        public {dispatcherName}({qualifiedInterface} service)");
        sb.AppendLine("        {");
        sb.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public string ServiceName => \"{service.ServiceName}\";");

        EmitDispatchAsync(sb, service, qualifiedInterface, isInstanceScoped: false);
        EmitDispatchAsync(sb, service, qualifiedInterface, isInstanceScoped: true);

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string QualifyServiceType(ServiceModel service, string typeName) =>
        string.IsNullOrEmpty(service.Namespace)
            ? "global::" + typeName
            : $"global::{service.Namespace}.{typeName}";

    /// <summary>
    /// Emits either <c>DispatchAsync</c> (singleton case) or <c>DispatchOnInstanceAsync</c>
    /// (instance case). Both share the same switch body — only the receiver expression
    /// differs (<c>_service</c> vs the registry-resolved instance).
    /// </summary>
    private static void EmitDispatchAsync(StringBuilder sb, ServiceModel service, string qualifiedInterface, bool isInstanceScoped)
    {
        sb.AppendLine();
        // CS1998: when every method on the service is sync the body has no `await`, but
        // we must keep the async return type to satisfy the interface contract.
        sb.AppendLine("#pragma warning disable CS1998");
        if (isInstanceScoped)
        {
            sb.AppendLine("        public async global::System.Threading.Tasks.Task<byte[]> DispatchOnInstanceAsync(string instanceId, string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Threading.CancellationToken ct = default)");
        }
        else
        {
            sb.AppendLine("        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Threading.CancellationToken ct = default)");
        }
        sb.AppendLine("#pragma warning restore CS1998");
        sb.AppendLine("        {");

        string receiver;
        if (isInstanceScoped)
        {
            sb.AppendLine($"            if (!registry.TryGet(\"{service.ServiceName}\", instanceId, out var __obj) || __obj is not {qualifiedInterface} __inst)");
            sb.AppendLine("            {");
            sb.AppendLine($"                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException(\"Instance '\" + instanceId + \"' not found for service '{service.ServiceName}'.\");");
            sb.AppendLine("            }");
            receiver = "__inst";
        }
        else
        {
            receiver = "_service";
        }

        sb.AppendLine("            switch (method)");
        sb.AppendLine("            {");

        foreach (var m in service.Methods.Array)
        {
            GenerateDispatchCase(sb, service, m, receiver);
        }

        sb.AppendLine("                default:");
        sb.AppendLine($"                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException(\"Method '\" + method + \"' not found on service '{service.ServiceName}'.\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void GenerateDispatchCase(StringBuilder sb, ServiceModel service, MethodModel method, string receiver)
    {
        // Methods whose shape we cannot marshal (ref/in/out parameters) get no switch case;
        // an inbound call for them falls through to the default ShaRpcNotFoundException
        // branch, which is the same behaviour as calling an unknown method name.
        if (method.UnsupportedReason is not null)
        {
            return;
        }

        sb.AppendLine($"                case \"{method.RpcName}\":");
        sb.AppendLine("                {");

        var requestParameters = GetRequestParameters(method.Parameters);
        if (requestParameters.Count == 1)
        {
            sb.AppendLine($"                    var arg = serializer.Deserialize<{requestParameters[0].Type}>(payload);");
        }
        else if (requestParameters.Count > 1)
        {
            var tupleTypes = new StringBuilder();
            for (var i = 0; i < requestParameters.Count; i++)
            {
                if (i > 0) tupleTypes.Append(", ");
                tupleTypes.Append(requestParameters[i].Type);
            }

            sb.AppendLine($"                    var args = serializer.Deserialize<({tupleTypes})>(payload);");
        }

        var argList = new StringBuilder();
        var requestIndex = 0;
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0) argList.Append(", ");

            var parameter = method.Parameters[i];
            if (parameter.IsCancellationToken)
            {
                argList.Append("ct");
            }
            else if (requestParameters.Count == 1)
            {
                argList.Append("arg");
                requestIndex++;
            }
            else
            {
                requestIndex++;
                argList.Append("args.Item").Append(requestIndex);
            }
        }

        var call = $"{receiver}.{method.Name}({argList})";

        switch (method.ReturnKind)
        {
            case MethodReturnKind.Void:
                sb.AppendLine($"                    {call};");
                sb.AppendLine("                    return global::System.Array.Empty<byte>();");
                break;

            case MethodReturnKind.Sync:
                sb.AppendLine($"                    var result = {call};");
                sb.AppendLine("                    return serializer.Serialize(result);");
                break;

            case MethodReturnKind.Task:
            case MethodReturnKind.ValueTask:
                sb.AppendLine($"                    await {call};");
                sb.AppendLine("                    return global::System.Array.Empty<byte>();");
                break;

            case MethodReturnKind.TaskOf:
            case MethodReturnKind.ValueTaskOf:
                sb.AppendLine($"                    var result = await {call};");
                sb.AppendLine("                    return serializer.Serialize(result);");
                break;

            case MethodReturnKind.TaskOfSubService:
            case MethodReturnKind.ValueTaskOfSubService:
            {
                // Sub-service return: don't serialize the live instance; instead register
                // it with the per-connection registry and ship back a ServiceHandle the
                // client can wrap in a sub-proxy.
                var info = method.SubService!;
                sb.AppendLine($"                    var __sub = await {call};");
                sb.AppendLine($"                    var __subId = registry.Register(\"{info.ServiceName}\", __sub);");
                sb.AppendLine($"                    return serializer.Serialize(new global::ShaRPC.Core.Protocol.ServiceHandle {{ ServiceName = \"{info.ServiceName}\", InstanceId = __subId }});");
                break;
            }
        }

        sb.AppendLine("                }");
    }

    private static List<ParameterModel> GetRequestParameters(EquatableArray<ParameterModel> parameters)
    {
        var requestParameters = new List<ParameterModel>();
        foreach (var p in parameters.Array)
        {
            if (!p.IsCancellationToken)
            {
                requestParameters.Add(p);
            }
        }

        return requestParameters;
    }
}
