using System.Text;
using System.Threading;

namespace ShaRPC.SourceGenerator;

internal static class GeneratedFactoryGenerator
{
    public static string Generate(EquatableArray<ServiceIdentity> services, CancellationToken ct = default)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ShaRPC.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Factory methods for ShaRPC-generated proxies and dispatchers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class ShaRpcGenerated");
        sb.AppendLine("    {");
        sb.AppendLine("        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedService[] s_services =");
        sb.AppendLine("        {");

        foreach (var service in services.Array)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Dispatcher");

            sb.AppendLine("            new global::ShaRPC.Core.Generated.ShaRpcGeneratedService(");
            sb.AppendLine($"                typeof({fullInterfaceName}),");
            sb.AppendLine($"                typeof({fullProxyName}),");
            sb.AppendLine($"                typeof({fullDispatcherName}),");
            sb.AppendLine($"                \"{LiteralHelpers.EscapeStringLiteral(service.ServiceName)}\"),");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        static ShaRpcGenerated()");
        sb.AppendLine("        {");
        sb.AppendLine("            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.RegisterServices(");
        sb.AppendLine("                typeof(global::ShaRPC.Generated.ShaRpcGenerated).Assembly,");
        sb.AppendLine("                s_services);");

        for (var i = 0; i < services.Array.Length; i++)
        {
            ct.ThrowIfCancellationRequested();
            var service = services.Array[i];
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Dispatcher");

            sb.AppendLine($"            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.Register<{fullInterfaceName}>(");
            sb.AppendLine($"                static client => new {fullProxyName}(client),");
            sb.AppendLine($"                static implementation => new {fullDispatcherName}(({fullInterfaceName})implementation),");
            sb.AppendLine($"                s_services[{i.ToString(System.Globalization.CultureInfo.InvariantCulture)}]);");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets the services generated into this assembly without scanning for generated types.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::ShaRPC.Core.Generated.ShaRpcGeneratedService> Services");
        sb.AppendLine("            => s_services;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds generated service proxy registrations to <paramref name=\"sink\" /> without scanning generated types.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void RegisterServices(global::ShaRPC.Core.Generated.IShaRpcServiceRegistrationSink sink)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sink is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(sink));");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var service in services.Array)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");

            sb.AppendLine($"            sink.AddService<{fullInterfaceName}, {fullProxyName}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Adds generated service proxy and dispatcher registrations to <paramref name=\"sink\" /> without scanning generated types.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void RegisterGeneratedServices(global::ShaRPC.Core.Generated.IShaRpcGeneratedServiceRegistrationSink sink)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sink is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(sink));");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var service in services.Array)
        {
            ct.ThrowIfCancellationRequested();
            var serviceName = NamingHelpers.StripInterfacePrefix(service.InterfaceName);
            var fullInterfaceName = IdentifierHelpers.QualifyTypeName(service.Namespace, service.InterfaceName);
            var fullProxyName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Proxy");
            var fullDispatcherName = IdentifierHelpers.QualifyTypeName(service.Namespace, serviceName + "Dispatcher");

            sb.AppendLine($"            sink.AddService<{fullInterfaceName}, {fullProxyName}, {fullDispatcherName}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated client proxy for <typeparamref name=\"TService\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static TService CreateProxy<TService>(global::ShaRPC.Core.Client.IShaRpcClient client)");
        sb.AppendLine("            where TService : class");
        sb.AppendLine("            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy<TService>(client);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated client proxy for <paramref name=\"serviceInterface\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static object CreateProxy(global::System.Type serviceInterface, global::ShaRPC.Core.Client.IShaRpcClient client)");
        sb.AppendLine("            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy(serviceInterface, client);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated server dispatcher for <paramref name=\"implementation\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)");
        sb.AppendLine("            where TService : class");
        sb.AppendLine("            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher<TService>(implementation);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Creates the generated server dispatcher for <paramref name=\"implementation\" />.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)");
        sb.AppendLine("            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher(serviceInterface, implementation);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
