using System.Text;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates client proxy classes for ShaRPC services. The generated proxy implements
/// the user's interface exactly — same return types, same parameter list, only adding
/// a forwarding body to <see cref="ShaRPC.Core.Client.IShaRpcClient"/>.
/// </summary>
internal static class ProxyGenerator
{
    public static string Generate(ServiceModel service)
    {
        var sb = new StringBuilder();
        var proxyName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Proxy";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ShaRPC.Core.Client;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Client proxy for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {proxyName} : {service.InterfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IShaRpcClient _client;");
        sb.AppendLine();
        sb.AppendLine($"        public {proxyName}(IShaRpcClient client)");
        sb.AppendLine("        {");
        sb.AppendLine("            _client = client ?? throw new ArgumentNullException(nameof(client));");
        sb.AppendLine("        }");

        foreach (var method in service.Methods.Array)
        {
            sb.AppendLine();
            GenerateProxyMethod(sb, service, method);
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GenerateProxyMethod(StringBuilder sb, ServiceModel service, MethodModel method)
    {
        // Build the parameter list exactly as it appears on the interface.
        var paramList = new StringBuilder();
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0)
            {
                paramList.Append(", ");
            }
            var p = method.Parameters[i];
            paramList.Append(p.Type).Append(' ').Append(p.Name);
        }
        if (method.HasCancellationToken)
        {
            if (paramList.Length > 0)
            {
                paramList.Append(", ");
            }
            paramList.Append("CancellationToken ct = default");
        }

        var declaredReturn = NamingHelpers.GetDeclaredReturnTypeText(method.ReturnKind, method.UnwrappedReturnType);
        var isAsync = method.ReturnKind == MethodReturnKind.Task || method.ReturnKind == MethodReturnKind.TaskOf;
        var asyncKeyword = isAsync ? "async " : string.Empty;
        var ctArg = method.HasCancellationToken ? "ct" : "default";

        sb.AppendLine($"        public {asyncKeyword}{declaredReturn} {method.Name}({paramList})");
        sb.AppendLine("        {");

        var invocation = BuildClientInvocation(service, method, ctArg);
        EmitInvocation(sb, method, invocation);

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Builds the call to <c>_client.InvokeAsync(...)</c>. The chosen overload depends on
    /// parameter count and the presence of a response payload, so the generated code
    /// uses the most direct overload available on <see cref="ShaRPC.Core.Client.IShaRpcClient"/>.
    /// </summary>
    private static string BuildClientInvocation(ServiceModel service, MethodModel method, string ctArg)
    {
        var hasReturn = method.ReturnKind == MethodReturnKind.Sync || method.ReturnKind == MethodReturnKind.TaskOf;
        var returnType = method.UnwrappedReturnType;

        if (method.Parameters.Count == 0)
        {
            // Use the no-request-payload overload.
            if (hasReturn)
            {
                return $"_client.InvokeAsync<{returnType}>(\"{service.ServiceName}\", \"{method.RpcName}\", {ctArg})";
            }

            // Void / Task without response: still call the no-payload overload and discard.
            return $"_client.InvokeAsync<object>(\"{service.ServiceName}\", \"{method.RpcName}\", {ctArg})";
        }

        if (method.Parameters.Count == 1)
        {
            var p = method.Parameters[0];
            if (hasReturn)
            {
                return $"_client.InvokeAsync<{p.Type}, {returnType}>(\"{service.ServiceName}\", \"{method.RpcName}\", {p.Name}, {ctArg})";
            }

            return $"_client.InvokeAsync<{p.Type}>(\"{service.ServiceName}\", \"{method.RpcName}\", {p.Name}, {ctArg})";
        }

        // Multiple parameters — pack into a ValueTuple payload.
        var tupleTypes = new StringBuilder();
        var tupleValues = new StringBuilder();
        for (var i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0)
            {
                tupleTypes.Append(", ");
                tupleValues.Append(", ");
            }
            tupleTypes.Append(method.Parameters[i].Type);
            tupleValues.Append(method.Parameters[i].Name);
        }

        if (hasReturn)
        {
            return $"_client.InvokeAsync<({tupleTypes}), {returnType}>(\"{service.ServiceName}\", \"{method.RpcName}\", ({tupleValues}), {ctArg})";
        }

        return $"_client.InvokeAsync<({tupleTypes})>(\"{service.ServiceName}\", \"{method.RpcName}\", ({tupleValues}), {ctArg})";
    }

    private static void EmitInvocation(StringBuilder sb, MethodModel method, string invocation)
    {
        switch (method.ReturnKind)
        {
            case MethodReturnKind.Void:
                // Sync void — block on the discarded response.
                sb.AppendLine($"            {invocation}.GetAwaiter().GetResult();");
                break;

            case MethodReturnKind.Sync:
                // Sync T — block on the response.
                sb.AppendLine($"            return {invocation}.GetAwaiter().GetResult();");
                break;

            case MethodReturnKind.Task:
                sb.AppendLine($"            await {invocation};");
                break;

            case MethodReturnKind.TaskOf:
                sb.AppendLine($"            return await {invocation};");
                break;
        }
    }
}
