using System.Text;
using System.Threading;

namespace ShaRPC.SourceGenerator;

/// <summary>
/// Generates client proxy classes for ShaRPC services. The generated proxy implements
/// the user's interface exactly — same return types, same parameter list, only adding
/// a forwarding body to <see cref="ShaRPC.Core.Client.IShaRpcClient"/>. All emitted
/// type references are fully qualified with <c>global::</c> so the generated file
/// never depends on the user's <c>using</c> set.
/// </summary>
internal static class ProxyGenerator
{
    public static string Generate(
        ServiceModel service,
        EquatableArray<AsyncSiblingMethod> siblingMethods,
        CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        var proxyName = NamingHelpers.StripInterfacePrefix(service.InterfaceName) + "Proxy";
        var qualifiedInterface = QualifyServiceType(service, service.InterfaceName);
        var qualifiedAsyncSibling = QualifyServiceType(
            service,
            NamingHelpers.AsyncSiblingInterfaceName(service.InterfaceName));

        // The proxy class implements both the user's interface and the generated async
        // sibling so callers can pick the blocking or non-blocking view.
        var baseList = siblingMethods.IsEmpty
            ? qualifiedInterface
            : $"{qualifiedInterface}, {qualifiedAsyncSibling}";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {IdentifierHelpers.EscapeNamespace(service.Namespace)}");
            sb.AppendLine("{");
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Client proxy for {service.InterfaceName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public sealed class {proxyName} : {baseList}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;");
        sb.AppendLine("        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>");
        sb.AppendLine("        private readonly string? _instanceId;");
        sb.AppendLine();
        sb.AppendLine($"        public {proxyName}(global::ShaRPC.Core.Client.IShaRpcClient client)");
        sb.AppendLine("        {");
        sb.AppendLine("            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));");
        sb.AppendLine("            this._instanceId = null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>");
        sb.AppendLine($"        public {proxyName}(global::ShaRPC.Core.Client.IShaRpcClient client, string instanceId)");
        sb.AppendLine("        {");
        sb.AppendLine("            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));");
        sb.AppendLine("            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));");
        sb.AppendLine("        }");

        foreach (var method in service.Methods.Array)
        {
            ct.ThrowIfCancellationRequested();
            sb.AppendLine();
            GenerateProxyMethod(sb, service, method, proxyName, ct);
        }

        foreach (var s in siblingMethods.Array)
        {
            ct.ThrowIfCancellationRequested();
            if (!s.RequiresExtraProxyMethod &&
                !ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(s.Name, proxyName))
            {
                continue;
            }

            sb.AppendLine();
            GenerateAsyncSiblingMethod(sb, service, s, proxyName, qualifiedAsyncSibling, ct);
        }

        sb.AppendLine("    }");

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
    private static string QualifyServiceType(ServiceModel service, string typeName) =>
        IdentifierHelpers.QualifyTypeName(service.Namespace, typeName);

    private static void GenerateProxyMethod(
        StringBuilder sb,
        ServiceModel service,
        MethodModel method,
        string proxyName,
        CancellationToken ct)
    {
        var paramList = new StringBuilder();
        ProxyGenerationHelpers.AppendParameterList(paramList, method.Parameters, ct);

        var declaredReturn = NamingHelpers.GetDeclaredReturnTypeText(method.ReturnKind, method.UnwrappedReturnType);
        var isAsync = NamingHelpers.IsAsync(method.ReturnKind);
        // Stubs stay non-async so out-parameters are definitely assigned by throw.
        var asyncKeyword = (isAsync && method.UnsupportedReason is null) ? "async " : string.Empty;
        var unsafeKeyword = method.RequiresUnsafeSignature ? "unsafe " : string.Empty;
        var ctArg = ProxyGenerationHelpers.GetCancellationTokenArgument(method.Parameters, ct);
        var explicitInterface = ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(method.Name, proxyName);
        var access = explicitInterface ? string.Empty : "public ";
        var target = explicitInterface ? method.ExplicitImplementationType + "." + method.Name : method.Name;

        sb.AppendLine($"        {access}{unsafeKeyword}{asyncKeyword}{method.ReturnRefKindKeyword}{declaredReturn} {target}{method.TypeParameterList}({paramList}){method.ConstraintClauses}");
        sb.AppendLine("        {");

        if (method.UnsupportedReason is not null)
        {
            sb.AppendLine($"            throw new global::System.NotSupportedException(\"ShaRPC cannot marshal '{method.Name}': {LiteralHelpers.EscapeStringLiteral(method.UnsupportedReason)}\");");
        }
        else
        {
            var invocation = BuildClientInvocation(service, method, ctArg, ct);
            EmitInvocation(sb, method, invocation, ct);
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Builds the call to <c>_client.InvokeAsync</c> or <c>_client.InvokeOnInstanceAsync</c>.
    /// For sub-service-returning methods, the wire response type is always
    /// <c>ServiceHandle</c>; the caller wraps it in a generated sub-proxy. The emitted
    /// expression branches on <c>_instanceId</c> so the same proxy class can serve both
    /// the top-level and the nested-instance call paths.
    /// </summary>
    private static string BuildClientInvocation(
        ServiceModel service,
        MethodModel method,
        string ctArg,
        CancellationToken ct)
    {
        var isSubServiceReturn = NamingHelpers.IsSubServiceReturn(method.ReturnKind);
        var hasReturn = NamingHelpers.HasReturnValue(method.ReturnKind);
        var returnType = isSubServiceReturn
            ? "global::ShaRPC.Core.Protocol.ServiceHandle"
            : method.UnwrappedReturnType is null
                ? null
                : ProxyGenerationHelpers.GetWireType(method.UnwrappedReturnType);
        var requestParameters = ProxyGenerationHelpers.GetRequestParameters(method.Parameters, ct);
        var svc = service.ServiceName;
        var rpc = method.RpcName;

        // Build the type-parameter list and argument list once; switch between the two
        // overload prefixes via the ternary.
        string typeArgs;
        string callArgs;        // arguments after (service, method) for the singleton overload
        string callArgsInst;    // arguments after (service, instanceId, method) for instance

        if (requestParameters.Count == 0)
        {
            if (hasReturn)
            {
                typeArgs = $"<{returnType}>";
                callArgs = $"\"{svc}\", \"{rpc}\", {ctArg}";
                callArgsInst = $"\"{svc}\", this._instanceId!, \"{rpc}\", {ctArg}";
            }
            else
            {
                typeArgs = "<object>";
                callArgs = $"\"{svc}\", \"{rpc}\", new object(), {ctArg}";
                callArgsInst = $"\"{svc}\", this._instanceId!, \"{rpc}\", new object(), {ctArg}";
            }
        }
        else if (requestParameters.Count == 1)
        {
            var p = requestParameters[0];
            var wireType = ProxyGenerationHelpers.GetWireType(p.Type);
            var wireArgument = ProxyGenerationHelpers.GetWireArgument(p);
            typeArgs = hasReturn ? $"<{wireType}, {returnType}>" : $"<{wireType}>";
            callArgs = $"\"{svc}\", \"{rpc}\", {wireArgument}, {ctArg}";
            callArgsInst = $"\"{svc}\", this._instanceId!, \"{rpc}\", {wireArgument}, {ctArg}";
        }
        else
        {
            var tupleTypes = new StringBuilder();
            var tupleValues = new StringBuilder();
            for (var i = 0; i < requestParameters.Count; i++)
            {
                ct.ThrowIfCancellationRequested();

                if (i > 0)
                {
                    tupleTypes.Append(", ");
                    tupleValues.Append(", ");
                }
                tupleTypes.Append(ProxyGenerationHelpers.GetWireType(requestParameters[i].Type));
                tupleValues.Append(ProxyGenerationHelpers.GetWireArgument(requestParameters[i]));
            }

            typeArgs = hasReturn ? $"<({tupleTypes}), {returnType}>" : $"<({tupleTypes})>";
            callArgs = $"\"{svc}\", \"{rpc}\", ({tupleValues}), {ctArg}";
            callArgsInst = $"\"{svc}\", this._instanceId!, \"{rpc}\", ({tupleValues}), {ctArg}";
        }

        return $"(this._instanceId is null ? this._client.InvokeAsync{typeArgs}({callArgs}) : this._client.InvokeOnInstanceAsync{typeArgs}({callArgsInst}))";
    }

    /// <summary>
    /// Emits a non-blocking proxy method that satisfies the async sibling interface.
    /// Reuses the underlying RPC call site of the original method (same service, same
    /// wire method name) but returns a Task / Task&lt;T&gt; so the caller never blocks.
    /// </summary>
    private static void GenerateAsyncSiblingMethod(
        StringBuilder sb,
        ServiceModel service,
        AsyncSiblingMethod s,
        string proxyName,
        string qualifiedAsyncSibling,
        CancellationToken ct)
    {
        var paramList = new StringBuilder();
        ProxyGenerationHelpers.AppendParameterList(paramList, s.Parameters, ct);

        var declaredReturn = NamingHelpers.GetDeclaredReturnTypeText(
            s.SiblingReturnKind, s.Source.UnwrappedReturnType);
        var explicitInterface = ProxyGenerationHelpers.MethodNameRequiresExplicitImplementation(s.Name, proxyName);
        var access = explicitInterface ? string.Empty : "public ";
        var target = explicitInterface ? qualifiedAsyncSibling + "." + s.Name : s.Name;

        sb.AppendLine($"        {access}async {declaredReturn} {target}({paramList})");
        sb.AppendLine("        {");

        // For the wire call, treat the sibling as having a CancellationToken AND the
        // sibling's return kind (so the invocation picks the right overload).
        var virtualSource = s.Source with
        {
            HasCancellationToken = true,
            ReturnKind = s.SiblingReturnKind,
            Parameters = s.Parameters,
        };
        var invocation = BuildClientInvocation(
            service,
            virtualSource,
            ProxyGenerationHelpers.GetCancellationTokenArgument(s.Parameters, ct),
            ct);
        EmitInvocation(sb, virtualSource, invocation, ct);

        sb.AppendLine("        }");
    }

    private static void EmitInvocation(
        StringBuilder sb,
        MethodModel method,
        string invocation,
        CancellationToken ct)
    {
        switch (method.ReturnKind)
        {
            case MethodReturnKind.Void:
                sb.AppendLine($"            {invocation}.GetAwaiter().GetResult();");
                break;

            case MethodReturnKind.Sync:
                sb.AppendLine($"            return {invocation}.GetAwaiter().GetResult();");
                break;

            case MethodReturnKind.Task:
            case MethodReturnKind.ValueTask:
                sb.AppendLine($"            await {invocation};");
                break;

            case MethodReturnKind.TaskOf:
            case MethodReturnKind.ValueTaskOf:
                sb.AppendLine($"            return await {invocation};");
                break;

            case MethodReturnKind.TaskOfSubService:
            case MethodReturnKind.ValueTaskOfSubService:
            {
                // Wire response is a ServiceHandle; wrap it in the generated sub-proxy.
                // The sub-proxy class lives in the SAME namespace as its interface, named
                // {StripI(InterfaceName)}Proxy — derived from SubService.QualifiedInterfaceName.
                var info = method.SubService!;
                var subProxyType = ProxyGenerationHelpers.BuildSubProxyTypeName(info.QualifiedInterfaceName);
                var handleName = ProxyGenerationHelpers.UniqueGeneratedLocalName(
                    method.Parameters,
                    "__sharpc_handle",
                    ct);
                sb.AppendLine($"            var {handleName} = await {invocation};");
                sb.AppendLine($"            return new {subProxyType}(this._client, {handleName}.InstanceId);");
                break;
            }
        }
    }
}
