//HintName: Snap_Kw_IKwSnap.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Kw
{
    /// <summary>
    /// Server dispatcher for IKwSnap.
    /// </summary>
    public sealed class KwSnapDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Kw.IKwSnap _service;

        public KwSnapDispatcher(global::Snap.Kw.IKwSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IKwSnap";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "DoAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await _service.DoAsync(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IKwSnap'.");
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IKwSnap", instanceId, out var __obj) || __obj is not global::Snap.Kw.IKwSnap __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IKwSnap'.");
            }
            switch (method)
            {
                case "DoAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await __inst.DoAsync(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IKwSnap'.");
            }
        }
    }
}
