//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a IRefOutSnap implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideRefOutSnap(this global::ShaRPC.Core.RpcPeer peer, global::Snap.RefOut.IRefOutSnap implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.RefOut.RefOutSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IRefOutSnap on the other peer.
        /// </summary>
        public static global::Snap.RefOut.IRefOutSnap GetRefOutSnap(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.RefOut.RefOutSnapProxy(peer);
    }
}
