//HintName: Snap_RefOut_IRefOutSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.RefOut
{
    /// <summary>
    /// Client proxy for IRefOutSnap.
    /// </summary>
    public sealed class RefOutSnapProxy : global::Snap.RefOut.IRefOutSnap
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public RefOutSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public void BadOut(out int x)
        {
            throw new global::System.NotSupportedException("ShaRPC cannot marshal 'BadOut': parameter 'x' uses an unsupported pass-by-reference kind 'out'");
        }

        public async global::System.Threading.Tasks.Task<int> GoodAsync(int a)
        {
            return await _client.InvokeAsync<int, int>("IRefOutSnap", "GoodAsync", a, default);
        }
    }
}
