//HintName: IMix.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Serialization;
using ShaRPC.Core.Server;
using ShaRPC.Core.Exceptions;

namespace Snap.Mixed
{
    /// <summary>
    /// Server dispatcher for IMix.
    /// </summary>
    public sealed class MixDispatcher : IServiceDispatcher
    {
        private readonly IMix _service;

        public MixDispatcher(IMix service)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IMix";

#pragma warning disable CS1998
        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "GetNameAsync":
                {
                    var result = await _service.GetNameAsync();
                    return serializer.Serialize(result);
                }
                case "SaveAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    await _service.SaveAsync(arg);
                    return Array.Empty<byte>();
                }
                case "SyncAdd":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = _service.SyncAdd(args.Item1, args.Item2);
                    return serializer.Serialize(result);
                }
                case "SyncPing":
                {
                    _service.SyncPing();
                    return Array.Empty<byte>();
                }
                default:
                    throw new ShaRpcNotFoundException($"Method '{method}' not found on service 'IMix'.");
            }
        }
    }
}
