//HintName: ICalculator.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Client;

namespace Snap.One
{
    /// <summary>
    /// Client proxy for ICalculator.
    /// </summary>
    public sealed class CalculatorProxy : ICalculator
    {
        private readonly IShaRpcClient _client;

        public CalculatorProxy(IShaRpcClient client)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
        }

        public async Task<int> AddAsync(int a, int b)
        {
            return await _client.InvokeAsync<(int, int), int>("ICalculator", "AddAsync", (a, b), default);
        }
    }
}
