//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IVtSnap.
        /// </summary>
        public static global::Snap.Vt.IVtSnap CreateVtSnapProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Vt.VtSnapProxy(client);

        /// <summary>
        /// Registers IVtSnap with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddVtSnap(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Vt.IVtSnap implementation)
            => builder.AddDispatcher(new global::Snap.Vt.VtSnapDispatcher(implementation));
    }
}
