//HintName: Snap_Vt_IVtSnap.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Server dispatcher for IVtSnap.
    /// </summary>
    public sealed class VtSnapDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher, global::ShaRPC.Core.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.Vt.IVtSnap _service;

        public VtSnapDispatcher(global::Snap.Vt.IVtSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IVtSnap";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::ShaRPC.Core.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::ShaRPC.Core.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var __sharpc_task = _service.AddAsync(args.Item1, args.Item2);
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                case "PingAsync":
                {
                    var __sharpc_task = _service.PingAsync();
                    if (!__sharpc_task.IsCompletedSuccessfully)
                    {
                        await __sharpc_task;
                        return;
                    }
                    __sharpc_task.GetAwaiter().GetResult();
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IVtSnap'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::ShaRPC.Core.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::ShaRPC.Core.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IVtSnap", instanceId, out var __obj) || __obj is not global::Snap.Vt.IVtSnap __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IVtSnap'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Instance);
            }
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var __sharpc_task = __inst.AddAsync(args.Item1, args.Item2);
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                case "PingAsync":
                {
                    var __sharpc_task = __inst.PingAsync();
                    if (!__sharpc_task.IsCompletedSuccessfully)
                    {
                        await __sharpc_task;
                        return;
                    }
                    __sharpc_task.GetAwaiter().GetResult();
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IVtSnap'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
