//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a IOne implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideOne(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Two.IOne implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Two.OneDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IOne on the other peer.
        /// </summary>
        public static global::Snap.Two.IOne GetOne(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Two.OneProxy(peer);

        /// <summary>
        /// Provides a ITwo implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideTwo(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Two.ITwo implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Two.TwoDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call ITwo on the other peer.
        /// </summary>
        public static global::Snap.Two.ITwo GetTwo(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Two.TwoProxy(peer);
    }
}
