//HintName: IMix.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Client;

namespace Snap.Mixed
{
    /// <summary>
    /// Client proxy for IMix.
    /// </summary>
    public sealed class MixProxy : IMix
    {
        private readonly IShaRpcClient _client;

        public MixProxy(IShaRpcClient client)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
        }

        public async Task<string> GetNameAsync()
        {
            return await _client.InvokeAsync<string>("IMix", "GetNameAsync", default);
        }

        public async Task SaveAsync(string value)
        {
            await _client.InvokeAsync<string>("IMix", "SaveAsync", value, default);
        }

        public int SyncAdd(int a, int b)
        {
            return _client.InvokeAsync<(int, int), int>("IMix", "SyncAdd", (a, b), default).GetAwaiter().GetResult();
        }

        public void SyncPing()
        {
            _client.InvokeAsync<object>("IMix", "SyncPing", default).GetAwaiter().GetResult();
        }
    }
}
