//HintName: Snap_Mixed_IMix.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Server dispatcher for IMix.
    /// </summary>
    public sealed class MixDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher, global::ShaRPC.Core.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.Mixed.IMix _service;

        public MixDispatcher(global::Snap.Mixed.IMix service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IMix";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::ShaRPC.Core.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::ShaRPC.Core.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "GetNameAsync":
                {
                    var __sharpc_task = _service.GetNameAsync();
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                case "SaveAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var __sharpc_task = _service.SaveAsync(arg);
                    if (!__sharpc_task.IsCompletedSuccessfully)
                    {
                        await __sharpc_task;
                    }
                    return;
                }
                case "SyncAdd":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = _service.SyncAdd(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                case "SyncPing":
                {
                    _service.SyncPing();
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IMix'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::ShaRPC.Core.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::ShaRPC.Core.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IMix", instanceId, out var __obj) || __obj is not global::Snap.Mixed.IMix __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IMix'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Instance);
            }
            switch (method)
            {
                case "GetNameAsync":
                {
                    var __sharpc_task = __inst.GetNameAsync();
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                case "SaveAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var __sharpc_task = __inst.SaveAsync(arg);
                    if (!__sharpc_task.IsCompletedSuccessfully)
                    {
                        await __sharpc_task;
                    }
                    return;
                }
                case "SyncAdd":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = __inst.SyncAdd(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                case "SyncPing":
                {
                    __inst.SyncPing();
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IMix'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
