//HintName: Snap_Kw_IKwSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Kw
{
    /// <summary>
    /// Client proxy for IKwSnap.
    /// </summary>
    public sealed class KwSnapProxy : global::Snap.Kw.IKwSnap
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public KwSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public async global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default)
        {
            return await _client.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), default);
        }
    }
}
