//HintName: Snap_One_ICalculator.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.One
{
    /// <summary>
    /// Server dispatcher for ICalculator.
    /// </summary>
    public sealed class CalculatorDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.One.ICalculator _service;

        public CalculatorDispatcher(global::Snap.One.ICalculator service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "ICalculator";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await _service.AddAsync(args.Item1, args.Item2);
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($"Method '{method}' not found on service 'ICalculator'.");
            }
        }
    }
}
