//HintName: Snap_Inherit_IDerived.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Server dispatcher for IDerived.
    /// </summary>
    public sealed class DerivedDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher, global::ShaRPC.Core.Server.INonStreamingServiceDispatcher
    {
        private readonly global::Snap.Inherit.IDerived _service;

        public DerivedDispatcher(global::Snap.Inherit.IDerived service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IDerived";

        public global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchAsync(method, payload, serializer, registry, output, global::ShaRPC.Core.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::ShaRPC.Core.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "DerivedAsync":
                {
                    var __sharpc_task = _service.DerivedAsync();
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                case "BaseAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var __sharpc_task = _service.BaseAsync(arg);
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IDerived'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }

        public global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default) =>
            DispatchOnInstanceAsync(instanceId, method, payload, serializer, registry, output, global::ShaRPC.Core.Streaming.RpcStreamingContext.Disabled, ct);

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::ShaRPC.Core.Streaming.IRpcStreamingContext streaming, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IDerived", instanceId, out var __obj) || __obj is not global::Snap.Inherit.IDerived __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IDerived'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Instance);
            }
            switch (method)
            {
                case "DerivedAsync":
                {
                    var __sharpc_task = __inst.DerivedAsync();
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                case "BaseAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var __sharpc_task = __inst.BaseAsync(arg);
                    var __sharpc_result = __sharpc_task.IsCompletedSuccessfully
                        ? __sharpc_task.Result
                        : await __sharpc_task;
                    serializer.Serialize(output, __sharpc_result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IDerived'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
