//HintName: Snap_Two_ITwo.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Two
{
    /// <summary>
    /// Server dispatcher for ITwo.
    /// </summary>
    public sealed class TwoDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Two.ITwo _service;

        public TwoDispatcher(global::Snap.Two.ITwo service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "ITwo";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "BAsync":
                {
                    var result = await _service.BAsync();
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'ITwo'.");
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchOnInstanceAsync(string instanceId, string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("ITwo", instanceId, out var __obj) || __obj is not global::Snap.Two.ITwo __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'ITwo'.");
            }
            switch (method)
            {
                case "BAsync":
                {
                    var result = await __inst.BAsync();
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'ITwo'.");
            }
        }
    }
}
