//HintName: ShaRpcGenerated.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Factory methods for ShaRPC-generated proxies and dispatchers.
    /// </summary>
    public static class ShaRpcGenerated
    {
        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedService[] s_services =
        {
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedService(
                typeof(global::Snap.Vt.IVtSnap),
                typeof(global::Snap.Vt.VtSnapProxy),
                typeof(global::Snap.Vt.VtSnapDispatcher),
                "IVtSnap"),
        };

        static ShaRpcGenerated()
        {
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.RegisterServices(
                typeof(global::ShaRPC.Generated.ShaRpcGenerated).Assembly,
                s_services);
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.Register<global::Snap.Vt.IVtSnap>(
                static client => new global::Snap.Vt.VtSnapProxy(client),
                static implementation => new global::Snap.Vt.VtSnapDispatcher((global::Snap.Vt.IVtSnap)implementation),
                s_services[0]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::ShaRPC.Core.Generated.ShaRpcGeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::ShaRPC.Core.Generated.IShaRpcServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Vt.IVtSnap, global::Snap.Vt.VtSnapProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::ShaRPC.Core.Generated.IShaRpcGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Vt.IVtSnap, global::Snap.Vt.VtSnapProxy, global::Snap.Vt.VtSnapDispatcher>();
        }

        /// <summary>
        /// Creates the generated client proxy for <typeparamref name="TService" />.
        /// </summary>
        public static TService CreateProxy<TService>(global::ShaRPC.Core.Client.IShaRpcClient client)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy<TService>(client);

        /// <summary>
        /// Creates the generated client proxy for <paramref name="serviceInterface" />.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::ShaRPC.Core.Client.IShaRpcClient client)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy(serviceInterface, client);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
