//HintName: Snap_Inherit_IDerived.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Server dispatcher for IDerived.
    /// </summary>
    public sealed class DerivedDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Inherit.IDerived _service;

        public DerivedDispatcher(global::Snap.Inherit.IDerived service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IDerived";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "DerivedAsync":
                {
                    var result = await _service.DerivedAsync();
                    return serializer.Serialize(result);
                }
                case "BaseAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await _service.BaseAsync(arg);
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($"Method '{method}' not found on service 'IDerived'.");
            }
        }
    }
}
