//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IDerived.
        /// </summary>
        public static global::Snap.Inherit.IDerived CreateDerivedProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.Inherit.DerivedProxy(client);

        /// <summary>
        /// Registers IDerived with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddDerived(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.Inherit.IDerived implementation)
            => builder.AddDispatcher(new global::Snap.Inherit.DerivedDispatcher(implementation));
    }
}
