//HintName: IOne.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Client;

namespace Snap.Two
{
    /// <summary>
    /// Client proxy for IOne.
    /// </summary>
    public sealed class OneProxy : IOne
    {
        private readonly IShaRpcClient _client;

        public OneProxy(IShaRpcClient client)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
        }

        public async Task<int> AAsync(int x)
        {
            return await _client.InvokeAsync<int, int>("IOne", "AAsync", x, default);
        }
    }
}
