//HintName: Snap_Mixed_IMix.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Client proxy for IMix.
    /// </summary>
    public sealed class MixProxy : global::Snap.Mixed.IMix
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public MixProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public async global::System.Threading.Tasks.Task<string> GetNameAsync()
        {
            return await _client.InvokeAsync<string>("IMix", "GetNameAsync", default);
        }

        public async global::System.Threading.Tasks.Task SaveAsync(string value)
        {
            await _client.InvokeAsync<string>("IMix", "SaveAsync", value, default);
        }

        public int SyncAdd(int a, int b)
        {
            return _client.InvokeAsync<(int, int), int>("IMix", "SyncAdd", (a, b), default).GetAwaiter().GetResult();
        }

        public void SyncPing()
        {
            _client.InvokeAsync<object>("IMix", "SyncPing", new object(), default).GetAwaiter().GetResult();
        }
    }
}
