//HintName: IHello.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Client;

namespace Snap.Renamed
{
    /// <summary>
    /// Client proxy for IHello.
    /// </summary>
    public sealed class HelloProxy : IHello
    {
        private readonly IShaRpcClient _client;

        public HelloProxy(IShaRpcClient client)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
        }

        public async Task<string> HelloAsync(string who)
        {
            return await _client.InvokeAsync<string, string>("Greeter", "Greet", who, default);
        }
    }
}
