//HintName: Snap_Inherit_IDerived.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Server dispatcher for IDerived.
    /// </summary>
    public sealed class DerivedDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Inherit.IDerived _service;

        public DerivedDispatcher(global::Snap.Inherit.IDerived service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IDerived";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "DerivedAsync":
                {
                    var result = await _service.DerivedAsync();
                    serializer.Serialize(output, result);
                    return;
                }
                case "BaseAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await _service.BaseAsync(arg);
                    serializer.Serialize(output, result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IDerived'.");
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IDerived", instanceId, out var __obj) || __obj is not global::Snap.Inherit.IDerived __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IDerived'.");
            }
            switch (method)
            {
                case "DerivedAsync":
                {
                    var result = await __inst.DerivedAsync();
                    serializer.Serialize(output, result);
                    return;
                }
                case "BaseAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await __inst.BaseAsync(arg);
                    serializer.Serialize(output, result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IDerived'.");
            }
        }
    }
}
