//HintName: IHello.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Serialization;
using ShaRPC.Core.Server;
using ShaRPC.Core.Exceptions;

namespace Snap.Renamed
{
    /// <summary>
    /// Server dispatcher for IHello.
    /// </summary>
    public sealed class HelloDispatcher : IServiceDispatcher
    {
        private readonly IHello _service;

        public HelloDispatcher(IHello service)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
        }

        public string ServiceName => "Greeter";

#pragma warning disable CS1998
        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "Greet":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var result = await _service.HelloAsync(arg);
                    return serializer.Serialize(result);
                }
                default:
                    throw new ShaRpcNotFoundException($"Method '{method}' not found on service 'Greeter'.");
            }
        }
    }
}
