//HintName: Snap_Nested_ISubSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Client proxy for ISubSnap.
    /// </summary>
    public sealed class SubSnapProxy : global::Snap.Nested.ISubSnap, global::Snap.Nested.ISubSnapAsync
    {
        private readonly global::ShaRPC.Core.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public SubSnapProxy(global::ShaRPC.Core.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public SubSnapProxy(global::ShaRPC.Core.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<int> CountAsync()
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<int>("ISubSnap", "CountAsync", default) : this._invoker.InvokeOnInstanceAsync<int>("ISubSnap", this._instanceId!, "CountAsync", default));
        }

        public async global::System.Threading.Tasks.Task<int> CountAsync(global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<int>("ISubSnap", "CountAsync", ct) : this._invoker.InvokeOnInstanceAsync<int>("ISubSnap", this._instanceId!, "CountAsync", ct));
        }
    }
}
