//HintName: Snap_One_ICalculator.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.One
{
    /// <summary>
    /// Client proxy for ICalculator.
    /// </summary>
    public sealed class CalculatorProxy : global::Snap.One.ICalculator, global::Snap.One.ICalculatorAsync
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public CalculatorProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public CalculatorProxy(global::ShaRPC.Core.Client.IShaRpcClient client, string instanceId)
        {
            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<int> AddAsync(int a, int b)
        {
            return await (this._instanceId is null ? this._client.InvokeAsync<(int, int), int>("ICalculator", "AddAsync", (a, b), default) : this._client.InvokeOnInstanceAsync<(int, int), int>("ICalculator", this._instanceId!, "AddAsync", (a, b), default));
        }

        public async global::System.Threading.Tasks.Task<int> AddAsync(int a, int b, global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._client.InvokeAsync<(int, int), int>("ICalculator", "AddAsync", (a, b), ct) : this._client.InvokeOnInstanceAsync<(int, int), int>("ICalculator", this._instanceId!, "AddAsync", (a, b), ct));
        }
    }
}
