//HintName: Snap_Vt_IVtSnap.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Server dispatcher for IVtSnap.
    /// </summary>
    public sealed class VtSnapDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Vt.IVtSnap _service;

        public VtSnapDispatcher(global::Snap.Vt.IVtSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IVtSnap";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await _service.AddAsync(args.Item1, args.Item2);
                    return serializer.Serialize(result);
                }
                case "PingAsync":
                {
                    await _service.PingAsync();
                    return global::System.Array.Empty<byte>();
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IVtSnap'.");
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchOnInstanceAsync(string instanceId, string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IVtSnap", instanceId, out var __obj) || __obj is not global::Snap.Vt.IVtSnap __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IVtSnap'.");
            }
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await __inst.AddAsync(args.Item1, args.Item2);
                    return serializer.Serialize(result);
                }
                case "PingAsync":
                {
                    await __inst.PingAsync();
                    return global::System.Array.Empty<byte>();
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IVtSnap'.");
            }
        }
    }
}
