//HintName: Snap_Nested_IRootSnap.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Nested
{
    /// <summary>
    /// Server dispatcher for IRootSnap.
    /// </summary>
    public sealed class RootSnapDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Nested.IRootSnap _service;

        public RootSnapDispatcher(global::Snap.Nested.IRootSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IRootSnap";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "GetSubAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var __sub = await _service.GetSubAsync(arg);
                    var __subId = registry.Register("ISubSnap", __sub);
                    serializer.Serialize(output, new global::ShaRPC.Core.Protocol.ServiceHandle { ServiceName = "ISubSnap", InstanceId = __subId });
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IRootSnap'.");
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IRootSnap", instanceId, out var __obj) || __obj is not global::Snap.Nested.IRootSnap __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IRootSnap'.");
            }
            switch (method)
            {
                case "GetSubAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var __sub = await __inst.GetSubAsync(arg);
                    var __subId = registry.Register("ISubSnap", __sub);
                    serializer.Serialize(output, new global::ShaRPC.Core.Protocol.ServiceHandle { ServiceName = "ISubSnap", InstanceId = __subId });
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IRootSnap'.");
            }
        }
    }
}
