//HintName: Snap_Renamed_IHello.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Renamed
{
    /// <summary>
    /// Client proxy for IHello.
    /// </summary>
    public sealed class HelloProxy : global::Snap.Renamed.IHello, global::Snap.Renamed.IHelloAsync
    {
        private readonly global::ShaRPC.Core.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public HelloProxy(global::ShaRPC.Core.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public HelloProxy(global::ShaRPC.Core.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<string> HelloAsync(string who)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<string, string>("Greeter", "Greet", who, default) : this._invoker.InvokeOnInstanceAsync<string, string>("Greeter", this._instanceId!, "Greet", who, default));
        }

        public async global::System.Threading.Tasks.Task<string> HelloAsync(string who, global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<string, string>("Greeter", "Greet", who, ct) : this._invoker.InvokeOnInstanceAsync<string, string>("Greeter", this._instanceId!, "Greet", who, ct));
        }
    }
}
