//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a IHello implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideHello(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Renamed.IHello implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Renamed.HelloDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IHello on the other peer.
        /// </summary>
        public static global::Snap.Renamed.IHello GetHello(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Renamed.HelloProxy(peer);
    }
}
