//HintName: Snap_Two_IOne.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Two
{
    /// <summary>
    /// Client proxy for IOne.
    /// </summary>
    public sealed class OneProxy : global::Snap.Two.IOne
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public OneProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public async global::System.Threading.Tasks.Task<int> AAsync(int x)
        {
            return await _client.InvokeAsync<int, int>("IOne", "AAsync", x, default);
        }
    }
}
