//HintName: Snap_RefOut_IRefOutSnap.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.RefOut
{
    /// <summary>
    /// Server dispatcher for IRefOutSnap.
    /// </summary>
    public sealed class RefOutSnapDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.RefOut.IRefOutSnap _service;

        public RefOutSnapDispatcher(global::Snap.RefOut.IRefOutSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IRefOutSnap";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "GoodAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await _service.GoodAsync(arg);
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($"Method '{method}' not found on service 'IRefOutSnap'.");
            }
        }
    }
}
