//HintName: IOne.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Serialization;
using ShaRPC.Core.Server;
using ShaRPC.Core.Exceptions;

namespace Snap.Two
{
    /// <summary>
    /// Server dispatcher for IOne.
    /// </summary>
    public sealed class OneDispatcher : IServiceDispatcher
    {
        private readonly IOne _service;

        public OneDispatcher(IOne service)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IOne";

#pragma warning disable CS1998
        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await _service.AAsync(arg);
                    return serializer.Serialize(result);
                }
                default:
                    throw new ShaRpcNotFoundException($"Method '{method}' not found on service 'IOne'.");
            }
        }
    }
}
