//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Creates a proxy for IRefOutSnap.
        /// </summary>
        public static global::Snap.RefOut.IRefOutSnap CreateRefOutSnapProxy(this global::ShaRPC.Core.Client.IShaRpcClient client)
            => new global::Snap.RefOut.RefOutSnapProxy(client);

        /// <summary>
        /// Registers IRefOutSnap with the server.
        /// </summary>
        public static global::ShaRPC.Core.Server.ShaRpcServerBuilder AddRefOutSnap(this global::ShaRPC.Core.Server.ShaRpcServerBuilder builder, global::Snap.RefOut.IRefOutSnap implementation)
            => builder.AddDispatcher(new global::Snap.RefOut.RefOutSnapDispatcher(implementation));
    }
}
