//HintName: Snap_Mixed_IMix.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Server dispatcher for IMix.
    /// </summary>
    public sealed class MixDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Mixed.IMix _service;

        public MixDispatcher(global::Snap.Mixed.IMix service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IMix";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "GetNameAsync":
                {
                    var result = await _service.GetNameAsync();
                    return serializer.Serialize(result);
                }
                case "SaveAsync":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    await _service.SaveAsync(arg);
                    return global::System.Array.Empty<byte>();
                }
                case "SyncAdd":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = _service.SyncAdd(args.Item1, args.Item2);
                    return serializer.Serialize(result);
                }
                case "SyncPing":
                {
                    _service.SyncPing();
                    return global::System.Array.Empty<byte>();
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($"Method '{method}' not found on service 'IMix'.");
            }
        }
    }
}
