//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a ICalculator implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideCalculator(this global::ShaRPC.Core.RpcPeer peer, global::Snap.One.ICalculator implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.One.CalculatorDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call ICalculator on the other peer.
        /// </summary>
        public static global::Snap.One.ICalculator GetCalculator(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.One.CalculatorProxy(peer);
    }
}
