//HintName: Snap_Mixed_IMix.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Mixed
{
    /// <summary>
    /// Client proxy for IMix.
    /// </summary>
    public sealed class MixProxy : global::Snap.Mixed.IMix, global::Snap.Mixed.IMixAsync
    {
        private readonly global::ShaRPC.Core.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public MixProxy(global::ShaRPC.Core.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public MixProxy(global::ShaRPC.Core.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<string> GetNameAsync()
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "GetNameAsync", default) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "GetNameAsync", default));
        }

        public async global::System.Threading.Tasks.Task SaveAsync(string value)
        {
            await (this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "SaveAsync", value, default) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "SaveAsync", value, default));
        }

        public int SyncAdd(int a, int b)
        {
            return (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IMix", "SyncAdd", (a, b), default) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IMix", this._instanceId!, "SyncAdd", (a, b), default)).GetAwaiter().GetResult();
        }

        public void SyncPing()
        {
            (this._instanceId is null ? this._invoker.InvokeAsync("IMix", "SyncPing", default) : this._invoker.InvokeOnInstanceAsync("IMix", this._instanceId!, "SyncPing", default)).GetAwaiter().GetResult();
        }

        public async global::System.Threading.Tasks.Task<string> GetNameAsync(global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "GetNameAsync", ct) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "GetNameAsync", ct));
        }

        public async global::System.Threading.Tasks.Task SaveAsync(string value, global::System.Threading.CancellationToken ct = default)
        {
            await (this._instanceId is null ? this._invoker.InvokeAsync<string>("IMix", "SaveAsync", value, ct) : this._invoker.InvokeOnInstanceAsync<string>("IMix", this._instanceId!, "SaveAsync", value, ct));
        }

        public async global::System.Threading.Tasks.Task<int> SyncAddAsync(int a, int b, global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<(int, int), int>("IMix", "SyncAdd", (a, b), ct) : this._invoker.InvokeOnInstanceAsync<(int, int), int>("IMix", this._instanceId!, "SyncAdd", (a, b), ct));
        }

        public async global::System.Threading.Tasks.Task SyncPingAsync(global::System.Threading.CancellationToken ct = default)
        {
            await (this._instanceId is null ? this._invoker.InvokeAsync("IMix", "SyncPing", ct) : this._invoker.InvokeOnInstanceAsync("IMix", this._instanceId!, "SyncPing", ct));
        }
    }
}
