//HintName: Snap_RefOut_IRefOutSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.RefOut
{
    /// <summary>
    /// Client proxy for IRefOutSnap.
    /// </summary>
    public sealed class RefOutSnapProxy : global::Snap.RefOut.IRefOutSnap, global::Snap.RefOut.IRefOutSnapAsync
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public RefOutSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            _instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public RefOutSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client, string instanceId)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            _instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public void BadOut(out int x)
        {
            throw new global::System.NotSupportedException("ShaRPC cannot marshal 'BadOut': parameter 'x' uses an unsupported pass-by-reference kind 'out'");
        }

        public async global::System.Threading.Tasks.Task<int> GoodAsync(int a)
        {
            return await (_instanceId is null ? _client.InvokeAsync<int, int>("IRefOutSnap", "GoodAsync", a, default) : _client.InvokeOnInstanceAsync<int, int>("IRefOutSnap", _instanceId, "GoodAsync", a, default));
        }

        public async global::System.Threading.Tasks.Task<int> GoodAsync(int a, global::System.Threading.CancellationToken ct = default)
        {
            return await (_instanceId is null ? _client.InvokeAsync<int, int>("IRefOutSnap", "GoodAsync", a, ct) : _client.InvokeOnInstanceAsync<int, int>("IRefOutSnap", _instanceId, "GoodAsync", a, ct));
        }
    }
}
