//HintName: ShaRpcGenerated.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Factory methods for ShaRPC-generated proxies and dispatchers.
    /// </summary>
    public static class ShaRpcGenerated
    {
        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedMethod[] s_service0Methods =
        {
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedMethod(
                "DoAsync",
                "DoAsync",
                typeof(global::System.Threading.Tasks.Task<int>),
                typeof(int),
                global::ShaRPC.Core.Generated.ShaRpcGeneratedReturnKind.TaskOfT,
                false,
                new global::ShaRPC.Core.Generated.ShaRpcGeneratedParameter[]
                {
                    new global::ShaRPC.Core.Generated.ShaRpcGeneratedParameter(
                        "class",
                        typeof(int),
                        0,
                        false,
                        false,
                        null),
                    new global::ShaRPC.Core.Generated.ShaRpcGeneratedParameter(
                        "default",
                        typeof(int),
                        1,
                        false,
                        false,
                        null),
                }),
        };

        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedService[] s_services =
        {
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedService(
                typeof(global::Snap.Kw.IKwSnap),
                typeof(global::Snap.Kw.KwSnapProxy),
                typeof(global::Snap.Kw.KwSnapDispatcher),
                "IKwSnap",
                s_service0Methods),
        };

        static ShaRpcGenerated()
        {
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.RegisterServices(
                typeof(global::ShaRPC.Generated.ShaRpcGenerated).Assembly,
                s_services);
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.Register<global::Snap.Kw.IKwSnap>(
                static client => new global::Snap.Kw.KwSnapProxy(client),
                static implementation => new global::Snap.Kw.KwSnapDispatcher((global::Snap.Kw.IKwSnap)implementation),
                s_services[0]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::ShaRPC.Core.Generated.ShaRpcGeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::ShaRPC.Core.Generated.IShaRpcServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Kw.IKwSnap, global::Snap.Kw.KwSnapProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::ShaRPC.Core.Generated.IShaRpcGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Kw.IKwSnap, global::Snap.Kw.KwSnapProxy, global::Snap.Kw.KwSnapDispatcher>();
        }

        /// <summary>
        /// Creates the generated proxy for <typeparamref name="TService" /> over an invoker.
        /// </summary>
        public static TService CreateProxy<TService>(global::ShaRPC.Core.IRpcInvoker invoker)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy<TService>(invoker);

        /// <summary>
        /// Creates the generated proxy for <paramref name="serviceInterface" /> over an invoker.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::ShaRPC.Core.IRpcInvoker invoker)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy(serviceInterface, invoker);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
