//HintName: Snap_Vt_IVtSnap.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Server dispatcher for IVtSnap.
    /// </summary>
    public sealed class VtSnapDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Vt.IVtSnap _service;

        public VtSnapDispatcher(global::Snap.Vt.IVtSnap service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IVtSnap";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await _service.AddAsync(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                case "PingAsync":
                {
                    await _service.PingAsync();
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IVtSnap'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IVtSnap", instanceId, out var __obj) || __obj is not global::Snap.Vt.IVtSnap __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IVtSnap'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Instance);
            }
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await __inst.AddAsync(args.Item1, args.Item2);
                    serializer.Serialize(output, result);
                    return;
                }
                case "PingAsync":
                {
                    await __inst.PingAsync();
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IVtSnap'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
