//HintName: Snap_Inherit_IDerived.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Client proxy for IDerived.
    /// </summary>
    public sealed class DerivedProxy : global::Snap.Inherit.IDerived, global::Snap.Inherit.IDerivedAsync
    {
        private readonly global::ShaRPC.Core.IRpcInvoker _invoker;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public DerivedProxy(global::ShaRPC.Core.IRpcInvoker client)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public DerivedProxy(global::ShaRPC.Core.IRpcInvoker client, string instanceId)
        {
            this._invoker = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<string> DerivedAsync()
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<string>("IDerived", "DerivedAsync", default) : this._invoker.InvokeOnInstanceAsync<string>("IDerived", this._instanceId!, "DerivedAsync", default));
        }

        public async global::System.Threading.Tasks.Task<int> BaseAsync(int x)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IDerived", "BaseAsync", x, default) : this._invoker.InvokeOnInstanceAsync<int, int>("IDerived", this._instanceId!, "BaseAsync", x, default));
        }

        public async global::System.Threading.Tasks.Task<string> DerivedAsync(global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<string>("IDerived", "DerivedAsync", ct) : this._invoker.InvokeOnInstanceAsync<string>("IDerived", this._instanceId!, "DerivedAsync", ct));
        }

        public async global::System.Threading.Tasks.Task<int> BaseAsync(int x, global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._invoker.InvokeAsync<int, int>("IDerived", "BaseAsync", x, ct) : this._invoker.InvokeOnInstanceAsync<int, int>("IDerived", this._instanceId!, "BaseAsync", x, ct));
        }
    }
}
