//HintName: Snap_Kw_IKwSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Kw
{
    /// <summary>
    /// Client proxy for IKwSnap.
    /// </summary>
    public sealed class KwSnapProxy : global::Snap.Kw.IKwSnap, global::Snap.Kw.IKwSnapAsync
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public KwSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public KwSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client, string instanceId)
        {
            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default)
        {
            return await (this._instanceId is null ? this._client.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), default) : this._client.InvokeOnInstanceAsync<(int, int), int>("IKwSnap", this._instanceId!, "DoAsync", (@class, @default), default));
        }

        public async global::System.Threading.Tasks.Task<int> DoAsync(int @class, int @default, global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._client.InvokeAsync<(int, int), int>("IKwSnap", "DoAsync", (@class, @default), ct) : this._client.InvokeOnInstanceAsync<(int, int), int>("IKwSnap", this._instanceId!, "DoAsync", (@class, @default), ct));
        }
    }
}
