//HintName: Snap_Two_IOne.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Two
{
    /// <summary>
    /// Server dispatcher for IOne.
    /// </summary>
    public sealed class OneDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Two.IOne _service;

        public OneDispatcher(global::Snap.Two.IOne service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IOne";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await _service.AAsync(arg);
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($"Method '{method}' not found on service 'IOne'.");
            }
        }
    }
}
