//HintName: Snap_Vt_IVtSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Client proxy for IVtSnap.
    /// </summary>
    public sealed class VtSnapProxy : global::Snap.Vt.IVtSnap, global::Snap.Vt.IVtSnapAsync
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;
        /// <summary>Non-null when this proxy targets a sub-service instance returned by a parent call.</summary>
        private readonly string? _instanceId;

        public VtSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = null;
        }

        /// <summary>Constructs a proxy bound to a specific server-side instance.</summary>
        public VtSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client, string instanceId)
        {
            this._client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            this._instanceId = instanceId ?? throw new global::System.ArgumentNullException(nameof(instanceId));
        }

        public async global::System.Threading.Tasks.ValueTask<int> AddAsync(int a, int b)
        {
            return await (this._instanceId is null ? this._client.InvokeAsync<(int, int), int>("IVtSnap", "AddAsync", (a, b), default) : this._client.InvokeOnInstanceAsync<(int, int), int>("IVtSnap", this._instanceId!, "AddAsync", (a, b), default));
        }

        public async global::System.Threading.Tasks.ValueTask PingAsync()
        {
            await (this._instanceId is null ? this._client.InvokeAsync<object>("IVtSnap", "PingAsync", new object(), default) : this._client.InvokeOnInstanceAsync<object>("IVtSnap", this._instanceId!, "PingAsync", new object(), default));
        }

        public async global::System.Threading.Tasks.ValueTask<int> AddAsync(int a, int b, global::System.Threading.CancellationToken ct = default)
        {
            return await (this._instanceId is null ? this._client.InvokeAsync<(int, int), int>("IVtSnap", "AddAsync", (a, b), ct) : this._client.InvokeOnInstanceAsync<(int, int), int>("IVtSnap", this._instanceId!, "AddAsync", (a, b), ct));
        }

        public async global::System.Threading.Tasks.ValueTask PingAsync(global::System.Threading.CancellationToken ct = default)
        {
            await (this._instanceId is null ? this._client.InvokeAsync<object>("IVtSnap", "PingAsync", new object(), ct) : this._client.InvokeOnInstanceAsync<object>("IVtSnap", this._instanceId!, "PingAsync", new object(), ct));
        }
    }
}
