//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a IKwSnap implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideKwSnap(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Kw.IKwSnap implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Kw.KwSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IKwSnap on the other peer.
        /// </summary>
        public static global::Snap.Kw.IKwSnap GetKwSnap(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Kw.KwSnapProxy(peer);
    }
}
