//HintName: ICalculator.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Serialization;
using ShaRPC.Core.Server;
using ShaRPC.Core.Exceptions;

namespace Snap.One
{
    /// <summary>
    /// Server dispatcher for ICalculator.
    /// </summary>
    public sealed class CalculatorDispatcher : IServiceDispatcher
    {
        private readonly ICalculator _service;

        public CalculatorDispatcher(ICalculator service)
        {
            _service = service ?? throw new ArgumentNullException(nameof(service));
        }

        public string ServiceName => "ICalculator";

#pragma warning disable CS1998
        public async Task<byte[]> DispatchAsync(string method, byte[] payload, ISerializer serializer, CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AddAsync":
                {
                    var args = serializer.Deserialize<(int, int)>(payload);
                    var result = await _service.AddAsync(args.Item1, args.Item2);
                    return serializer.Serialize(result);
                }
                default:
                    throw new ShaRpcNotFoundException($"Method '{method}' not found on service 'ICalculator'.");
            }
        }
    }
}
