//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a IMix implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideMix(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Mixed.IMix implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Mixed.MixDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IMix on the other peer.
        /// </summary>
        public static global::Snap.Mixed.IMix GetMix(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Mixed.MixProxy(peer);
    }
}
