//HintName: Snap_Two_IOne.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Two
{
    /// <summary>
    /// Server dispatcher for IOne.
    /// </summary>
    public sealed class OneDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Two.IOne _service;

        public OneDispatcher(global::Snap.Two.IOne service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "IOne";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchAsync(string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "AAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await _service.AAsync(arg);
                    serializer.Serialize(output, result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IOne'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task DispatchOnInstanceAsync(string instanceId, string method, global::System.ReadOnlyMemory<byte> payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::ShaRPC.Core.Server.IInstanceRegistry registry, global::System.Buffers.IBufferWriter<byte> output, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            if (!registry.TryGet("IOne", instanceId, out var __obj) || __obj is not global::Snap.Two.IOne __inst)
            {
                throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Instance '" + instanceId + "' not found for service 'IOne'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Instance);
            }
            switch (method)
            {
                case "AAsync":
                {
                    var arg = serializer.Deserialize<int>(payload);
                    var result = await __inst.AAsync(arg);
                    serializer.Serialize(output, result);
                    return;
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException("Method '" + method + "' not found on service 'IOne'.", global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException.NotFoundKind.Method);
            }
        }
    }
}
