//HintName: Snap_Renamed_IHello.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Renamed
{
    /// <summary>
    /// Client proxy for IHello.
    /// </summary>
    public sealed class HelloProxy : global::Snap.Renamed.IHello
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public HelloProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public async global::System.Threading.Tasks.Task<string> HelloAsync(string who)
        {
            return await _client.InvokeAsync<string, string>("Greeter", "Greet", who, default);
        }
    }
}
