//HintName: Snap_Renamed_IHello.ShaRpcDispatcher.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Renamed
{
    /// <summary>
    /// Server dispatcher for IHello.
    /// </summary>
    public sealed class HelloDispatcher : global::ShaRPC.Core.Server.IServiceDispatcher
    {
        private readonly global::Snap.Renamed.IHello _service;

        public HelloDispatcher(global::Snap.Renamed.IHello service)
        {
            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));
        }

        public string ServiceName => "Greeter";

#pragma warning disable CS1998
        public async global::System.Threading.Tasks.Task<byte[]> DispatchAsync(string method, byte[] payload, global::ShaRPC.Core.Serialization.ISerializer serializer, global::System.Threading.CancellationToken ct = default)
#pragma warning restore CS1998
        {
            switch (method)
            {
                case "Greet":
                {
                    var arg = serializer.Deserialize<string>(payload);
                    var result = await _service.HelloAsync(arg);
                    return serializer.Serialize(result);
                }
                default:
                    throw new global::ShaRPC.Core.Exceptions.ShaRpcNotFoundException($"Method '{method}' not found on service 'Greeter'.");
            }
        }
    }
}
