//HintName: ShaRpcExtensions.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Extension methods for registering generated ShaRPC services.
    /// </summary>
    public static class ShaRpcGeneratedExtensions
    {

        /// <summary>
        /// Provides a IRootSnap implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideRootSnap(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Nested.IRootSnap implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Nested.RootSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call IRootSnap on the other peer.
        /// </summary>
        public static global::Snap.Nested.IRootSnap GetRootSnap(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Nested.RootSnapProxy(peer);

        /// <summary>
        /// Provides a ISubSnap implementation for the other peer to call.
        /// </summary>
        public static global::ShaRPC.Core.RpcPeer ProvideSubSnap(this global::ShaRPC.Core.RpcPeer peer, global::Snap.Nested.ISubSnap implementation)
            => peer.Provide((global::ShaRPC.Core.Server.IServiceDispatcher)new global::Snap.Nested.SubSnapDispatcher(implementation));

        /// <summary>
        /// Gets a proxy to call ISubSnap on the other peer.
        /// </summary>
        public static global::Snap.Nested.ISubSnap GetSubSnap(this global::ShaRPC.Core.RpcPeer peer)
            => new global::Snap.Nested.SubSnapProxy(peer);
    }
}
