//HintName: Snap_Vt_IVtSnap.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Vt
{
    /// <summary>
    /// Client proxy for IVtSnap.
    /// </summary>
    public sealed class VtSnapProxy : global::Snap.Vt.IVtSnap
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public VtSnapProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public async global::System.Threading.Tasks.ValueTask<int> AddAsync(int a, int b)
        {
            return await _client.InvokeAsync<(int, int), int>("IVtSnap", "AddAsync", (a, b), default);
        }

        public async global::System.Threading.Tasks.ValueTask PingAsync()
        {
            await _client.InvokeAsync<object>("IVtSnap", "PingAsync", new object(), default);
        }
    }
}
