//HintName: ITwo.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using ShaRPC.Core.Client;

namespace Snap.Two
{
    /// <summary>
    /// Client proxy for ITwo.
    /// </summary>
    public sealed class TwoProxy : ITwo
    {
        private readonly IShaRpcClient _client;

        public TwoProxy(IShaRpcClient client)
        {
            _client = client ?? throw new ArgumentNullException(nameof(client));
        }

        public async Task<string> BAsync()
        {
            return await _client.InvokeAsync<string>("ITwo", "BAsync", default);
        }
    }
}
