//HintName: Snap_Inherit_IDerived.ShaRpcProxy.g.cs
// <auto-generated />
#nullable enable

namespace Snap.Inherit
{
    /// <summary>
    /// Client proxy for IDerived.
    /// </summary>
    public sealed class DerivedProxy : global::Snap.Inherit.IDerived
    {
        private readonly global::ShaRPC.Core.Client.IShaRpcClient _client;

        public DerivedProxy(global::ShaRPC.Core.Client.IShaRpcClient client)
        {
            _client = client ?? throw new global::System.ArgumentNullException(nameof(client));
        }

        public async global::System.Threading.Tasks.Task<string> DerivedAsync()
        {
            return await _client.InvokeAsync<string>("IDerived", "DerivedAsync", default);
        }

        public async global::System.Threading.Tasks.Task<int> BaseAsync(int x)
        {
            return await _client.InvokeAsync<int, int>("IDerived", "BaseAsync", x, default);
        }
    }
}
