//HintName: ShaRpcGenerated.g.cs
// <auto-generated />
#nullable enable

namespace ShaRPC.Generated
{
    /// <summary>
    /// Factory methods for ShaRPC-generated proxies and dispatchers.
    /// </summary>
    public static class ShaRpcGenerated
    {
        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedMethod[] s_service0Methods =
        {
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedMethod(
                "GetSubAsync",
                "GetSubAsync",
                typeof(global::System.Threading.Tasks.Task<global::Snap.Nested.ISubSnap>),
                typeof(global::Snap.Nested.ISubSnap),
                global::ShaRPC.Core.Generated.ShaRpcGeneratedReturnKind.TaskOfNestedService,
                true,
                new global::ShaRPC.Core.Generated.ShaRpcGeneratedParameter[]
                {
                    new global::ShaRPC.Core.Generated.ShaRpcGeneratedParameter(
                        "label",
                        typeof(string),
                        0,
                        false,
                        false,
                        null),
                }),
        };

        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedMethod[] s_service1Methods =
        {
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedMethod(
                "CountAsync",
                "CountAsync",
                typeof(global::System.Threading.Tasks.Task<int>),
                typeof(int),
                global::ShaRPC.Core.Generated.ShaRpcGeneratedReturnKind.TaskOfT,
                false,
                new global::ShaRPC.Core.Generated.ShaRpcGeneratedParameter[]
                {
                }),
        };

        private static readonly global::ShaRPC.Core.Generated.ShaRpcGeneratedService[] s_services =
        {
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedService(
                typeof(global::Snap.Nested.IRootSnap),
                typeof(global::Snap.Nested.RootSnapProxy),
                typeof(global::Snap.Nested.RootSnapDispatcher),
                "IRootSnap",
                s_service0Methods),
            new global::ShaRPC.Core.Generated.ShaRpcGeneratedService(
                typeof(global::Snap.Nested.ISubSnap),
                typeof(global::Snap.Nested.SubSnapProxy),
                typeof(global::Snap.Nested.SubSnapDispatcher),
                "ISubSnap",
                s_service1Methods),
        };

        static ShaRpcGenerated()
        {
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.RegisterServices(
                typeof(global::ShaRPC.Generated.ShaRpcGenerated).Assembly,
                s_services);
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.Register<global::Snap.Nested.IRootSnap>(
                static client => new global::Snap.Nested.RootSnapProxy(client),
                static implementation => new global::Snap.Nested.RootSnapDispatcher((global::Snap.Nested.IRootSnap)implementation),
                s_services[0]);
            global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.Register<global::Snap.Nested.ISubSnap>(
                static client => new global::Snap.Nested.SubSnapProxy(client),
                static implementation => new global::Snap.Nested.SubSnapDispatcher((global::Snap.Nested.ISubSnap)implementation),
                s_services[1]);
        }

        /// <summary>
        /// Gets the services generated into this assembly without scanning for generated types.
        /// </summary>
        public static global::System.Collections.Generic.IReadOnlyList<global::ShaRPC.Core.Generated.ShaRpcGeneratedService> Services
            => s_services;

        /// <summary>
        /// Adds generated service proxy registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterServices(global::ShaRPC.Core.Generated.IShaRpcServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Nested.IRootSnap, global::Snap.Nested.RootSnapProxy>();
            sink.AddService<global::Snap.Nested.ISubSnap, global::Snap.Nested.SubSnapProxy>();
        }

        /// <summary>
        /// Adds generated service proxy and dispatcher registrations to <paramref name="sink" /> without scanning generated types.
        /// </summary>
        public static void RegisterGeneratedServices(global::ShaRPC.Core.Generated.IShaRpcGeneratedServiceRegistrationSink sink)
        {
            if (sink is null)
            {
                throw new global::System.ArgumentNullException(nameof(sink));
            }

            sink.AddService<global::Snap.Nested.IRootSnap, global::Snap.Nested.RootSnapProxy, global::Snap.Nested.RootSnapDispatcher>();
            sink.AddService<global::Snap.Nested.ISubSnap, global::Snap.Nested.SubSnapProxy, global::Snap.Nested.SubSnapDispatcher>();
        }

        /// <summary>
        /// Creates the generated proxy for <typeparamref name="TService" /> over an invoker.
        /// </summary>
        public static TService CreateProxy<TService>(global::ShaRPC.Core.IRpcInvoker invoker)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy<TService>(invoker);

        /// <summary>
        /// Creates the generated proxy for <paramref name="serviceInterface" /> over an invoker.
        /// </summary>
        public static object CreateProxy(global::System.Type serviceInterface, global::ShaRPC.Core.IRpcInvoker invoker)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateProxy(serviceInterface, invoker);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher<TService>(TService implementation)
            where TService : class
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher<TService>(implementation);

        /// <summary>
        /// Creates the generated server dispatcher for <paramref name="implementation" />.
        /// </summary>
        public static global::ShaRPC.Core.Server.IServiceDispatcher CreateDispatcher(global::System.Type serviceInterface, object implementation)
            => global::ShaRPC.Core.Generated.ShaRpcServiceRegistry.CreateDispatcher(serviceInterface, implementation);
    }
}
